### ISSUE TITLE
Image/Activity Indicator Alignment Issues

### ISSUE THREAD

**Issue by nmock** [cruffenach/CRToast#131]
The alignment of the image/activity indicator aren't properly aligned with text. See attached screenshots from the demo app:

![img_1414](https://cloud.githubusercontent.com/assets/254881/5990985/b3c9b8a6-a984-11e4-82d6-7498bf3413b5.PNG)
![img_1416](https://cloud.githubusercontent.com/assets/254881/5990986/b3daef9a-a984-11e4-8c00-e02b8b2648c6.PNG)

**Comment by dmiedema** [comment]
Currently when the image or activity indicator is centered the text doesn't account for it.

I still haven't really thought of exactly how to handle it when both are desired to be centered and rather than making an assumption that the image/activity indicator should always fall to the left or right of text if there is any when both are centered, the text simply ignores it when calculating its frame.
